networks:
  default:
    name: daml_observability

services:

  pqs_scribe:
    container_name: daml_observability_pqs_scribe
    image: ${SCRIBE_IMAGE}:${SCRIBE_VERSION}
    volumes:
      - ./extras:/canton/host/configs:r
    command: pipeline ledger postgres-document --config /canton/host/configs/pqs_scribe.conf
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    #   canton:
    #     condition: service_healthy

  adminer:
    container_name: daml_observability_adminer
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    ports:
      - 8085:8080
