---
# Copyright 2022 Digital Asset (Switzerland) GmbH and/or its affiliates
#
# SPDX-License-Identifier: Apache-2.0
#
services:

  http-json:
    image: digitalasset/http-json:${SDK_VERSION}
    container_name: daml_observability_http_json
    build:
      context: daml-service
      dockerfile: Dockerfile
      args:
        SDK_VERSION: ${SDK_VERSION}
        DAML_SERVICE: http-json
    ports:
      # HTTP JSON API
      - 4001:4001
      # Prometheus exporter
      - 19091:19091
    environment:
      JDK_JAVA_OPTIONS: "-XX:+ExitOnOutOfMemoryError -Xmx1G"
    command:
      - "--config=/http-json/http-json.conf"
      - "--log-level=${LOG_LEVEL:-INFO}"
      - "--log-encoder=json"
    volumes:
      # Logs
      - logs:/var/log/promtail
      - ./http-json:/http-json
    healthcheck:
      # Requires curl in image
      test: "curl -f localhost:4001/livez && curl -f localhost:4001/readyz"
      interval: 5s
      timeout: 1s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
      canton:
        condition: service_healthy

  trigger-service:
    image: digitalasset/trigger-service:${SDK_VERSION}
    container_name: daml_observability_trigger_service
    build:
      context: daml-service
      dockerfile: Dockerfile
      args:
        SDK_VERSION: ${SDK_VERSION}
        DAML_SERVICE: trigger-service
    ports:
      - 4002:8088
      # Prometheus exporter
      - 19092:19090
    environment:
      JDK_JAVA_OPTIONS: "-XX:+ExitOnOutOfMemoryError -Xmx1G"
      LOG_LEVEL_ROOT: ${LOG_LEVEL:-INFO}
      LOG_FORMAT_JSON: "true"
    command:
      - "--config=/trigger-service/trigger-service.conf"
    volumes:
      # Logs
      - logs:/var/log/promtail
      - ./trigger-service:/trigger-service
    healthcheck:
      # Requires curl in image
      test: "curl -f localhost:4002/livez && curl -f localhost:4002/readyz"
      interval: 5s
      timeout: 1s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
      canton:
        condition: service_healthy
