{
 "title": "Commands",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values({__name__=~\".*daml_commands_delayed_submissions_total\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Valid submissions/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate({__name__=~\".*daml_commands_valid_submissions_total\", namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commands in flight (length + capacity)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=~\".*daml_commands_max_in_flight_length\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\".*daml_commands_max_in_flight_capacity\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total command processing time (quantiles)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "{__name__=~\".*daml_commands_submissions\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Command validation time (quantiles)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "{__name__=~\".*daml_commands_validation\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delayed submissions count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{__name__=~\".*daml_commands_delayed_submissions_total\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed command interpretations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "{__name__=~\".*daml_commands_failed_command_interpretations_total\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}