{
 "title": "PQS / Scribe",
 "description": "Dashboard for monitoring application metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prom_src", "label": "Source", "query": "prometheus" },
   {
    "name": "jvm_job",
    "label": "Job",
    "query": "label_values(jvm_cpu_time_seconds_total, job)"
   },
   {
    "name": "jvm_mempool",
    "label": "MemPool",
    "query": "label_values(jvm_memory_used_after_last_gc_bytes{job=\"$jvm_job\"}, jvm_memory_pool_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Contracts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Churn",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "label_replace(rate(pipeline_events_total{job=\"$jvm_job\",type=\"create\"}[$__rate_interval]) * 1, \"short_template\", \"$1\", \"template\", \".*?:(.*)\")",
       "legendFormat": "{{short_template}}"
      },
      {
       "expr": "label_replace(rate(pipeline_events_total{job=\"$jvm_job\",type=\"archive\"}[$__rate_interval]) * -1, \"short_template\", \"$1\", \"template\", \".*?:(.*)\")",
       "legendFormat": "{{short_template}}"
      }
     ]
    },
    {
     "title": "Active *",
     "type": "timeseries",
     "description": "* as observed since last restart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(sum without(type) (pipeline_events_total{job=\"$jvm_job\",type=\"create\"}) - ((sum without(type) (pipeline_events_total{job=\"$jvm_job\",type=\"archive\"})) or (sum without(type) (pipeline_events_total{job=\"$jvm_job\",type=\"create\"})*0)), \"short_template\", \"$1\", \"template\", \".*?:(.*)\")",
       "legendFormat": "{{short_template}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current watermark throughput",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "rate(watermark_ix{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "watermark index"
      }
     ]
    },
    {
     "title": "Current events throughput",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
     "targets": [
      {
       "expr": "sum(rate(pipeline_events_total{job=\"$jvm_job\",type=~\"(create|archive|exercise)\"}[$__rate_interval]))",
       "legendFormat": "events"
      }
     ]
    },
    {
     "title": "Ledger transactions ingested",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
     "targets": [
      {
       "expr": "watermark_ix{job=\"$jvm_job\"}"
      }
     ]
    },
    {
     "title": "Ledger events ingested",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
     "targets": [
      {
       "expr": "sum(pipeline_events_total{job=\"$jvm_job\",type=~\"(create|archive|exercise)\"})",
       "legendFormat": "events"
      }
     ]
    },
    {
     "title": "Watermark history",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(watermark_ix{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "watermark index"
      }
     ]
    },
    {
     "title": "Transactions and events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(pipeline_events_total{job=\"$jvm_job\",type=\"transaction\"}[$__rate_interval])",
       "legendFormat": "transactions"
      },
      {
       "expr": "sum(rate(pipeline_events_total{job=\"$jvm_job\",type=~\"(create|archive|exercise)\"}[$__rate_interval]))",
       "legendFormat": "events"
      }
     ]
    },
    {
     "title": "Events breakdown",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(pipeline_events_total{job=\"$jvm_job\",type=\"create\"}[$__rate_interval]))",
       "legendFormat": "creates"
      },
      {
       "expr": "sum(rate(pipeline_events_total{job=\"$jvm_job\",type=\"archive\"}[$__rate_interval]))",
       "legendFormat": "archives"
      },
      {
       "expr": "sum(rate(pipeline_events_total{job=\"$jvm_job\",type=\"exercise\"}[$__rate_interval]))",
       "legendFormat": "exercises"
      }
     ]
    },
    {
     "title": "Waitpoints - ACS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(pipeline_wp_acs_events_total{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "ledger events"
      },
      {
       "expr": "rate(pipeline_wp_acs_statements_total{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "statements"
      },
      {
       "expr": "rate(pipeline_wp_acs_batched_statements_total{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "batches"
      },
      {
       "expr": "rate(pipeline_wp_acs_prepared_statements_total{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "prepared statements"
      }
     ]
    },
    {
     "title": "Waitpoints - streaming",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(pipeline_wp_events_total{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "ledger events"
      },
      {
       "expr": "rate(pipeline_wp_statements_total{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "statements"
      },
      {
       "expr": "rate(pipeline_wp_batched_statements_total{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "batches"
      },
      {
       "expr": "rate(pipeline_wp_prepared_statements_total{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "prepared statements"
      },
      {
       "expr": "rate(pipeline_wp_watermarks_total{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "watermarks"
      }
     ]
    }
   ]
  },
  {
   "title": "Queues sizes - ACS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "rate(pipeline_wp_acs_events_size_bucket{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Statements",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "targets": [
      {
       "expr": "rate(pipeline_wp_acs_statements_size_bucket{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Batched statements",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "rate(pipeline_wp_acs_batched_statements_size_bucket{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Prepared statements",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "rate(pipeline_wp_acs_prepared_statements_size_bucket{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queues sizes - streaming",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "rate(pipeline_wp_events_size_bucket{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Statements",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "targets": [
      {
       "expr": "rate(pipeline_wp_statements_size_bucket{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Batched statements",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "rate(pipeline_wp_batched_statements_size_bucket{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Prepared statements",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "rate(pipeline_wp_prepared_statements_size_bucket{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Watermarks",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "rate(pipeline_wp_watermarks_size_bucket{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Convert event - ACS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by(le) (rate(pipeline_convert_acs_event_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum by(le) (rate(pipeline_convert_acs_event_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(pipeline_convert_acs_event_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(pipeline_convert_acs_event_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "rate(pipeline_convert_acs_event_count[$__rate_interval])",
       "legendFormat": "throughput"
      }
     ]
    },
    {
     "title": "Convert event - ACS",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "targets": [
      {
       "expr": "rate(pipeline_convert_acs_event_bucket{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Convert transaction - streaming",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by(le) (rate(pipeline_convert_transaction_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum by(le) (rate(pipeline_convert_transaction_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(pipeline_convert_transaction_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(pipeline_convert_transaction_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "rate(pipeline_convert_transaction_count[$__rate_interval])",
       "legendFormat": "throughput"
      }
     ]
    },
    {
     "title": "Convert transaction - streaming",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "rate(pipeline_convert_transaction_bucket{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Prepare batch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by(le) (rate(pipeline_prepare_batch_latency_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum by(le) (rate(pipeline_prepare_batch_latency_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(pipeline_prepare_batch_latency_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(pipeline_prepare_batch_latency_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "rate(pipeline_prepare_batch_latency_count[$__rate_interval])",
       "legendFormat": "throughput"
      }
     ]
    },
    {
     "title": "Prepare batch",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "rate(pipeline_prepare_batch_latency_bucket{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Execute batch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by(le) (rate(pipeline_execute_batch_latency_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum by(le) (rate(pipeline_execute_batch_latency_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(pipeline_execute_batch_latency_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(pipeline_execute_batch_latency_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "rate(pipeline_execute_batch_latency_count[$__rate_interval])",
       "legendFormat": "throughput"
      }
     ]
    },
    {
     "title": "Execute batch",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "rate(pipeline_execute_batch_latency_bucket{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Progress watermark",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by(le) (rate(pipeline_progress_watermark_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum by(le) (rate(pipeline_progress_watermark_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(pipeline_progress_watermark_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(pipeline_progress_watermark_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "rate(pipeline_progress_watermark_count[$__rate_interval])",
       "legendFormat": "throughput"
      }
     ]
    },
    {
     "title": "Progress watermark",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "rate(pipeline_progress_watermark_bucket{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "JDBC connection",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by(le) (rate(jdbc_conn_use_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum by(le) (rate(jdbc_conn_use_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(jdbc_conn_use_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(jdbc_conn_use_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "rate(jdbc_conn_use_count[$__rate_interval])",
       "legendFormat": "throughput"
      }
     ]
    },
    {
     "title": "JDBC connection",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "targets": [
      {
       "expr": "rate(jdbc_conn_use_bucket{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "JDBC connection (validity check)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by(le) (rate(jdbc_conn_isvalid_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum by(le) (rate(jdbc_conn_isvalid_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(jdbc_conn_isvalid_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(jdbc_conn_isvalid_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "rate(jdbc_conn_isvalid_count[$__rate_interval])",
       "legendFormat": "throughput"
      }
     ]
    },
    {
     "title": "JDBC connection (validity check)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "expr": "rate(jdbc_conn_isvalid_bucket{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "JDBC connection (commit)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by(le) (rate(jdbc_conn_commit_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum by(le) (rate(jdbc_conn_commit_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(jdbc_conn_commit_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(jdbc_conn_commit_bucket{job=\"$jvm_job\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "rate(jdbc_conn_commit_count[$__rate_interval])",
       "legendFormat": "throughput"
      }
     ]
    },
    {
     "title": "JDBC connection (commit)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "targets": [
      {
       "expr": "rate(jdbc_conn_commit_bucket{job=\"$jvm_job\"}[$__rate_interval])",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"$jvm_job\", jvm_memory_type=\"heap\"}) by(jvm_memory_type)",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{job=\"$jvm_job\", jvm_memory_type=\"heap\"}) by(jvm_memory_type)",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_limit_bytes{job=\"$jvm_job\", jvm_memory_type=\"heap\"}) by(jvm_memory_type)",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Garbage collection",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(idelta(jvm_gc_duration_seconds_count{job=\"$jvm_job\"}[$__rate_interval])) by(jvm_gc_name)",
       "legendFormat": "{{jvm_gc_name}} (count)"
      },
      {
       "expr": "sum(idelta(jvm_gc_duration_seconds_sum{job=\"$jvm_job\"}[$__rate_interval])) by(jvm_gc_name)",
       "legendFormat": "{{jvm_gc_name}} (time)"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_thread_count{job=\"$jvm_job\"}",
       "legendFormat": "{{jvm_thread_state}}"
      }
     ]
    },
    {
     "title": "Memory pool - $jvm_mempool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "repeat": "jvm_mempool",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{job=\"$jvm_job\", jvm_memory_pool_name=\"$jvm_mempool\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{job=\"$jvm_job\", jvm_memory_pool_name=\"$jvm_mempool\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_limit_bytes{job=\"$jvm_job\", jvm_memory_pool_name=\"$jvm_mempool\"}",
       "legendFormat": "max"
      },
      {
       "expr": "irate(jvm_memory_used_bytes{job=\"$jvm_job\", jvm_memory_pool_name=\"$jvm_mempool\"}[$__rate_interval])",
       "legendFormat": "allocated"
      }
     ]
    }
   ]
  }
 ]
}