{
 "title": "Participant Received Events",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_indexer_events_total, namespace)"
    }
   },
   {
    "name": "participant",
    "query": {
     "query": "label_values(daml_indexer_events_total{namespace=\"$namespace\"}, participant_id)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(daml_indexer_events_total{namespace=\"$namespace\",participant_id=~\"$participant\"}, application_id)"
    }
   },
   { "name": "group_by", "label": "Group by", "query": "participant_id,application_id" }
  ]
 },
 "panels": [
  {
   "title": "Received Events (e.g. transaction, package upload, party allocation)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by($group_by) (increase(daml_indexer_events_total{namespace=\"$namespace\", participant_id=~\"$participant\", application_id=~\"$application\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Successful Events",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Events / s" } },
   "targets": [
    {
     "expr": "sum by(${group_by:csv},event_type) (rate(daml_indexer_events_total{namespace=\"$namespace\", participant_id=~\"$participant\", application_id=~\"$application\", status=\"accepted\"}[$__rate_interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Rejection Events",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Events / s" } },
   "targets": [
    {
     "expr": "sum by(${group_by:csv},event_type, grpc_code) (rate(daml_indexer_events_total{namespace=\"$namespace\", participant_id=~\"$participant\", application_id=~\"$application\", status=\"rejected\"}[$__rate_interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}