{
 "title": "HTTP Endpoints",
 "tags": [ "daml" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "daml_http_requests_total" } },
   { "name": "path", "query": { "query": "daml_http_requests_total" } },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(path, service) (rate(daml_http_requests_total{service=~\"$service\", path=~\"$path\"}[$__rate_interval]))",
     "legendFormat": "{{service}}:{{path}}"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(http_status) (rate(daml_http_requests_total{service=~\"$service\", path=~\"$path\"}[1m]))",
     "legendFormat": "{{http_status}}"
    }
   ]
  },
  {
   "title": "HTTP Payload Bytes Received",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(le) (increase(daml_http_requests_payload_bytes_bucket{service=~\"$service\", path=~\"$path\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(path, service) (rate(daml_http_requests_total{service=~\"$service\", path=~\"$path\", http_status!=\"200\"}[$__rate_interval]))",
     "legendFormat": "{{service}}:{{path}}"
    }
   ]
  },
  {
   "title": "HTTP Payload Bytes Sent",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(le) (increase(daml_http_responses_payload_bytes_bucket{service=~\"$service\", path=~\"$path\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(daml_http_requests_duration_seconds_bucket{service=~\"$service\", path=~\"$path\"}[1m])))",
     "legendFormat": "50 percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(daml_http_requests_duration_seconds_bucket{service=~\"$service\", path=~\"$path\"}[1m])))",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(daml_http_requests_duration_seconds_bucket{service=~\"$service\", path=~\"$path\"}[1m])))",
     "legendFormat": "99 percentile"
    }
   ]
  },
  {
   "title": "Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by(le) (increase(daml_http_requests_duration_seconds_bucket{service=~\"$service\", path=~\"$path\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Websockets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Websocket Messages Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(path, service) (rate(daml_http_websocket_messages_received_total{service=~\"$service\", path=~\"$path\"}[1m]))",
     "legendFormat": "{{service}}:{{path}}"
    }
   ]
  },
  {
   "title": "Websocket Messages Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(path, service) (rate(daml_http_websocket_messages_sent_total{service=~\"$service\", path=~\"$path\"}[1m]))",
     "legendFormat": "{{service}}:{{path}}"
    }
   ]
  },
  {
   "title": "Websocket Bytes Received",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by(le) (increase(daml_http_websocket_messages_received_bytes_bucket{service=~\"$service\", path=~\"$path\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Websocket Bytes Sent",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum by(le) (increase(daml_http_websocket_messages_sent_bytes_bucket{service=~\"$service\", path=~\"$path\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}