{
 "title": "JVM Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(runtime_jvm_gc_count_total, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(runtime_jvm_gc_count_total{namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(runtime_jvm_gc_count_total{namespace=\"$namespace\"}, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GC Runs",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(gc, container, pod) (rate(runtime_jvm_gc_count_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "{{gc}} {{pod}} {{container}}"
    }
   ]
  },
  {
   "title": "GC Timing",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(gc, container, pod) (rate(runtime_jvm_gc_time_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "{{gc}} {{pod}} {{container}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Memory Area",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "runtime_jvm_memory_area{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "{{pod}} {{container}} - {{area}} - {{type}}"
    }
   ]
  },
  {
   "title": "Memory Pool",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "runtime_jvm_memory_pool{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "{{pod}} {{container}} - {{pool}} - {{type}}"
    }
   ]
  }
 ]
}