{
 "title": "Network Operation Center Health Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_grpc_server_started_total, namespace)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Participant Received Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(daml_indexer_events_total{event_type=\"transaction\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Participant Processed Events",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(daml_indexer_events_total{namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{application_id}}:{{event_type}}"
    }
   ]
  },
  {
   "title": "Participant Metered Events",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(daml_indexer_metered_events_total{namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{application_id}}"
    }
   ]
  },
  { "title": "gRPC Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Rate | All gRPC Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(daml_grpc_server_handled_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "all gRPC requests"
    }
   ]
  },
  {
   "title": "Return Code | All gRPC Requests",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "sum by(grpc_code) (rate(daml_grpc_server_handled_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency | All gRPC Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (daml_grpc_server_duration_seconds_bucket{namespace=\"$namespace\"}))",
     "legendFormat": "50 percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (daml_grpc_server_duration_seconds_bucket{namespace=\"$namespace\"}))",
     "legendFormat": "90 percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (daml_grpc_server_duration_seconds_bucket{namespace=\"$namespace\"}))",
     "legendFormat": "99 percentile"
    }
   ]
  },
  { "title": "HTTP Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Rate | All HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(daml_http_requests_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "all HTTP requests"
    }
   ]
  },
  {
   "title": "Status Code | All HTTP Requests",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "sum by(http_status) (rate(daml_http_requests_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency | All HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (daml_http_requests_duration_seconds_bucket{namespace=\"$namespace\"}))",
     "legendFormat": "50 percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (daml_http_requests_duration_seconds_bucket{namespace=\"$namespace\"}))",
     "legendFormat": "90 percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (daml_http_requests_duration_seconds_bucket{namespace=\"$namespace\"}))",
     "legendFormat": "99 percentile"
    }
   ]
  },
  { "title": "Top 5 Failures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Rejected Transactions | Top 5 Application IDs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "topk(5, sum by(application_id) (rate(daml_indexer_events_total{status=\"rejected\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "{{application_id}}"
    }
   ]
  },
  {
   "title": "gRPC Errors | Top 5 Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(5, sum by(grpc_service_name, grpc_method_name) (rate(daml_grpc_server_handled_total{grpc_code!=\"OK\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "{{grpc_service_name}}:{{grpc_method_name}}"
    }
   ]
  },
  {
   "title": "HTTP Errors | Top 5 Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(5, sum by(http_verb, path) (rate(daml_http_requests_total{http_status!~\"2..|1..\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "{{http_verb}}:{{path}}"
    }
   ]
  },
  { "title": "Misc.", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Websocket Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(daml_http_websocket_messages_received_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "message received"
    },
    {
     "expr": "sum(rate(daml_http_websocket_messages_sent_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "message sent"
    }
   ]
  },
  {
   "title": "Components' Status",
   "type": "status-history",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 41 },
   "targets": [
    {
     "expr": "daml_health_status{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM GC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 41 },
   "targets": [
    {
     "expr": "rate(jvm_garbage_collector_G1_Young_Generation_time{namespace=\"$namespace\"}[1m])/rate(jvm_garbage_collector_G1_Young_Generation_count{namespace=\"$namespace\"}[1m])",
     "legendFormat": "young generation"
    },
    {
     "expr": "rate(jvm_garbage_collector_G1_Old_Generation_time{namespace=\"$namespace\"}[1m])/rate(jvm_garbage_collector_G1_Old_Generation_count{namespace=\"$namespace\"}[1m])",
     "legendFormat": "old generation"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 50 },
   "options": {
    "content": "# Detailed Dashboards\n\n* Events: [Received](/d/1lW16xh4k)/[Metered](/d/6x7xtk2Vz)\n* [Components' Status](/d/IME_mP2Vk)\n* [gRPC Endpoints](/d/ODlOJFvVk)\n* [HTTP Endpoints](/d/NMeBCuH4k)\n* [JVM Metrics](/d/rgt7PhA4z)\n* [JVM Executor Services](/d/AYtzKz2Vz)"
   }
  }
 ]
}