---
version: 2.1

executors:
  docker:
    docker:
      - image: cimg/base:2023.03
    resource_class: small

commands:
  test_deployment:
    steps:
      - run: ./scripts/validate_deployment.sh

jobs:
  test_setup:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker images
          command: docker compose build
      - run:
          name: Pull docker images
          command: docker compose pull
      - run:
          background: true
          name: Start the compose setup
          command: docker compose up
      - test_deployment

workflows:
  test:
    jobs:
      - test_setup
