---
version: 2.1

executors:
  docker:
    docker:
      - image: curlimages/curl:8.00.0
    resource_class: small

commands:
  start_compose:
    steps:
      - compose: 
          run: docker compose up
  test_deployment:
    steps:
      - query_state:
          run: ./scripts/validate_deployment.sh

jobs:
  test_setup:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - start_compose:
          background: true
      - test_deployment

workflows:
  test:
    jobs:
      - test_setup
