---
version: 2.1

executors:
  docker:
    docker:
      - image: curlimages/curl:8.00.0
    resource_class: small

commands:
  test_deployment:
    steps:
      - query_state:
          run: ./scripts/validate_deployment.sh

jobs:
  test_setup:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          background: true
          name: Start the compose setup
          command: docker compose up
      - test_deployment

workflows:
  test:
    jobs:
      - test_setup
