---
version: 2.1

commands:

jobs:
  test:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Pull Docker images
          command: |
            docker compose pull --quiet --ignore-buildable
            docker pull --quiet azul/zulu-openjdk-debian:11
      - run:
          name: Build Docker images
          command: docker compose build
      - run:
          background: true
          name: Start Docker Compose in the background
          command: docker compose up --abort-on-container-exit
      - run:
          name: Test Docker Compose
          command: |
            ./scripts/validate-deployment.sh
      - run:
          name: Stop everything
          when: always
          command: docker compose down --volumes

workflows:
  Test Docker Compose:
    jobs:
      - test
