---
apiVersion: 1

datasources:
  # Prometheus
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus
    # Docker compose service
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: false
  # Loki
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    uid: loki
    # Docker compose service
    url: http://loki:5000
    isDefault: false
    version: 1
    editable: false
