{
 "title": "Subsystem Load",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(participant1_canton_db_storage_acs_commitment_queue_load, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sequencer counter tracker store load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{__name__=~\".*canton_db_storage_sequencer_counter_tracker_store_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequenced event store load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{__name__=~\".*canton_db_storage_sequenced_event_store_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Crypto store load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{__name__=~\".*canton_db_storage_crypto_private_store_insert_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\".*canton_db_storage_crypto_private_store_query_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\".*canton_db_storage_crypto_public_store_insert_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\".*canton_db_storage_crypto_public_store_query_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topology store load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{__name__=~\".*canton_db_storage_topology_store_read_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\".*canton_db_storage_topology_store_update_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Participants", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Active Contract Store load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{__name__=~\".*canton_db_storage_active_contract_store_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ACS commitment store load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "{__name__=~\".*canton_db_storage_acs_commitment_store_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ACS commitment queue load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{__name__=~\".*canton_db_storage_acs_commitment_queue_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ACS snapshot store load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "{__name__=~\".*_canton_db_storage_acs_snapshot_store_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contract store load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "{__name__=~\".*canton_db_storage_contract_store_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contract store query batcher",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "{__name__=~\".*_canton_db_storage_contract_store_query_batcher_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Command deduplication store load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "{__name__=~\".*canton_db_storage_command_deduplication_store_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Journal load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "{__name__=~\".*canton_db_storage_contract_key_journal_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\".*canton_db_storage_request_journal_store_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In-flight submission store load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "{__name__=~\".*canton_db_storage_in_flight_submission_store_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Domain store load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "{__name__=~\".*_canton_db_storage_domain_connection_config_store_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\".*_canton_db_storage_domain_parameter_store_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Party metadata store load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "{__name__=~\".*_canton_db_storage_party_metadata_store_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Setting store load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "{__name__=~\".*_canton_db_storage_participant_settings_store_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Single dimension event log load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "{__name__=~\".*canton_db_storage_single_dimension_event_log_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service agreement store load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "{__name__=~\".*_canton_db_storage_service_agreement_store_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer Client load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "{__name__=~\".*canton_mydomain_sequencer_client_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Submission tracker store load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "{__name__=~\".*canton_db_storage_submission_tracker_store_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfer store load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "{__name__=~\".*canton_db_storage_transfer_store_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Mediators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Finalized response store load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "{__name__=~\".*canton_db_storage_finalized_response_store_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deduplication store load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "{__name__=~\".*canton_db_storage_mediator_deduplication_store_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deduplication store query batcher load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "{__name__=~\".*canton_db_storage_mediator_deduplication_store_query_batcher_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer Client load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "expr": "{__name__=~\".*canton_mediator_sequencer_client_load\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}